project_id = "huawtqggkzujiptndmns"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[storage]
enabled = true

[functions.cart]
verify_jwt = false

[functions.checkout]
verify_jwt = false

[functions.tracking]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.request-balance-payment]
verify_jwt = true

[functions.whoami]
verify_jwt = false

[functions.analytics-config]
verify_jwt = false

[functions.validate-discount]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = true

[functions.purchase-gift-card]
verify_jwt = false

[functions.create-paysera-payment]
verify_jwt = false

[functions.paysera-callback]
verify_jwt = false

[functions.get-order-by-session]
verify_jwt = false

[functions.parcel-terminals]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false
